name: Run Datadog Synthetic tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # إجبار كل Actions على Node.js 24
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout أحدث نسخة من المستودع
      - name: Checkout repository
        uses: actions/checkout@v5

      # Run Datadog Synthetic tests
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@latest
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          test_search_query: 'tag:e2e-tests' # عدّل الوسم حسب استراتيجيتك
